### ISSUE TITLE
Scenario: Send token from ETH to cosmos

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#40]
📖     Epic to collect and discuss the steps needed.
This assumes bootstrapping and setup steps are all completed

## Happy path:
- [ ] Contract receives tokens and exposes an event on ETH
- [ ] Orchestrator watches events on ETH / or queries for updates
- [ ] Orchestrator sends Msg to cosmos for ETH token received event
- [x] Cosmos module persists state and mints token vouchers when oracle observes the event
- [x] Cosmos module emits an event for the operation

## Questions
- [ ] Do we need a back channel to the contract via orchestrator?

## Unhappy path
- [ ] Msgs not submitted to cosmos by orchestrator(s) so that the threshold not reached

**Comment by jkilpatr** [comment]
Got this all working in our brokennet test this weekend, closing because all we have now is bug reports and refinements.
