### ISSUE TITLE
Epic: My notepad for todos on the cosmos side

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#67]
Unsorted list - WIP

## Cosmos

- [x] Bug: order of signatures in querier must match addresses, order by power DESC #68 
- [ ] Remove deprecated methods and types (ValsetConfirm for example)
- [ ] Store orchestrator's cosmos address in peggy (https://github.com/althea-net/peggy/issues/44)
- [ ] Pass PeggyID to checkpoint methods
- [X] Implement checkpoint for batch
- [ ] Combined batch + valset checkpoint + endpoint for bridge contract's `updateValsetAndSubmitBatch` (see https://github.com/althea-net/peggy/issues/13)
- [ ] Reject votes for nonces <= last observed/ approved
- [ ] Trigger bridge Multisig update when ETH address is changed
- [ ] Trigger bridge Multisig update when validator power changes
- [ ] Handle invalid cosmos addresses on deposit
- [ ] Enforce ordered channel for deposits. No gaps on cosmos side allowed
- [ ] Authorization for orchestrators messages in handler
- [ ] Revisit events and response data on the cosmos side if they make sense for clients
- [ ] Proper payload and message validations
- [ ] Implement Attestation time out (block height or block time?)
- [ ] cancel any valset updates < last observed update (in attestation handler) 
- [ ] Delete legacy attestations, valsets in attestation post-processing
- [ ] Move attestation processing into post block handler
- [ ] Implement slashing (see https://github.com/althea-net/peggy/issues/42)
- [ ] discuss: the cosmos valset entry is a snapshot at time of creation. A validator may set his ETH address a block later but would be excluded in that round; Is there a problem with ETH address changes before submitting a signature?
- [ ] Implement Genesis IO
- [ ] Use the right electorate for attestations:
   - Current validators for oracles
   - Bootstrap valset for first approvals (unless we emit a bootstrap AND MultisigSet update event in the contract constructor)
   - Last MultisigSet for approvals after first observed MultisigSet
- [ ] Use persistent counter for MultiSig update nonce instead block height (see https://github.com/althea-net/peggy/issues/41)
- [ ] Handle "in-flight" MultiSig updates (optimistic/ pessimistic approach ?) (See https://github.com/althea-net/peggy/issues/62#issuecomment-703753527)
- [ ] Add a new message to notify "orchestrator has submitted tasks to Ethereum side" https://github.com/althea-net/peggy/issues/70#issuecomment-712669288 and ( another one) to notify about submission failures/ forks

- [ ] Add pagination to endpoints for clients
- [ ] Find and address remaining todos in the code
- [ ] Measure and optimise workflows for gas
- [ ] Store block height with observed event (orchestrator can use it to skip old events)
- [ ] Revisit claim submission by orchestrators to prevent any cheating
- [ ] Remove voucher denominator limitations (cut to 15 chars due to cosmos sdk length constraint)
- [ ] Upgrade cosmos sdk to stargate RC
- [ ] Handle unhappy scenarios for all processes
## Refactorings
- Better structure and UX
	- [ ] Querier.go
	- [ ] REST path
	- [ ] CLI commands/ queries
- Revisit claimTypes and Oracle and Approvals design as attestations (split?)

## Extensions
- [ ] Support most common queries with second indexes?
- [ ] Let a user cancel a TX that is not in a batch
- [ ] Create batches in post block handler based on some criteria that need to be defined

## Bridge Contract
- [ ] (Re-) define Events for orchestrator workflows (see contract in https://github.com/althea-net/peggy/pull/56)
- [ ] Batch nonce instead of TX nonces (See https://github.com/althea-net/peggy/issues/61)
- [ ] Contract should have counter nonce for deposits to enable ordered channel for deposits on the cosmos side

## Artifacts
- [ ] build and store release artifacts
